### PR TITLE
here is working version

### PR DESCRIPTION
**Pull request by volkirik**
I modified it to make it work

### CODE REVIEW

**Comment by joeytwiddle** [comment]
Cool. I will give it a try! Thanks. :)

**Comment by volkirik** [comment]
did you try?

feedback is welcome.

**Comment by joeytwiddle** [comment]
I did eventually try it today, on [this page](https://www.youtube.com/watch?v=RGILKOD5YI0#NOVA_18_demoparty) but it didn't find anything to work with. Specifically:

- It didn't find `#page-container` so it looked for `ytd-app` instead.
- But then `pagecontainer.innerHTML` was undefined, and `logoContainer` was also undefined, so it did nothing.

I tried waiting 5 seconds before running the start function, but the same result. I'm using Tampermonkey in Chrome.

I have a version based on this which sometimes works: https://github.com/nanojin/downloadyoutube/raw/master/script/yt.user.js

So I think I will revert to that, until something better comes along.

But these days, I have been using youtube-dl from the command-line instead.

**Comment by volkirik** [comment]
v2.2 workz fine for me. please let me know.
https://openuserjs.org/scripts/volkan-k/Download_YouTube_Videos_as_MP4

**Comment by joeytwiddle** [comment]
Today I tried this video: https://www.youtube.com/watch?v=lboPkSBmKPg

But I didn't see any Download button (I was looking near the thumbup/thumbdown buttons).

This is what got logged:

```
/watch?v=lboPkSBmKPg#Keyboarders_-_Life_on_the_grid:14 <link rel=preload> must have a valid `as` value
[Deprecation] Styling master document from stylesheets defined in HTML Imports is deprecated. Please refer to https://goo.gl/EGXzpw for possible migration paths.
userscript.html?id=3bc56f06-a390-44ac-909b-f2125f745067:960 DYVAM - Info: Standard mode. videoID lboPkSBmKPg; 
userscript.html?id=3bc56f06-a390-44ac-909b-f2125f745067:960 DYVAM - Info: url https://www.youtube.com/watch?v=lboPkSBmKPg#Keyboarders_-_Life_on_the_grid; useragent Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
userscript.html?id=3bc56f06-a390-44ac-909b-f2125f745067:960 DYVAM - Info: signature 3,28,-1,0,22 /yts/jsbin/player-vflunOvo8/en_US/base.js
userscript.html?id=3bc56f06-a390-44ac-909b-f2125f745067:960 DYVAM - Info: Full script URL: https://www.youtube.com/yts/jsbin/player-vflunOvo8/en_US/base.js
userscript.html?id=3bc56f06-a390-44ac-909b-f2125f745067:960 DYVAM - Info: itag18 url:https://r1---sn-nu5gi0c-npoe7.googlevideo.com/videoplayback?initcwndbps=2132500&ei=GLY5W9TqJMXMowOwh42AAw&dur=178.654&expire=1530530424&fexp=23709359&ipbits=0&mm=31,29&mn=sn-nu5gi0c-npoe7,sn-npoeen7k&mime=video/mp4&id=o-ALtrXRViexFZ7jujD8ukskDIuNytp0pDC9HRvhHzrsHb&pl=23&mt=1530508733&mv=m&ms=au,rdu&ip=58.182.52.103&requiressl=yes&c=WEB&signature=93495F76FDC915EE1EFAA1FA2AB69FD2EC9D12F7.0690195BC37F654846C7BA18434D52EF55FDD603&ratebypass=yes&gir=yes&fvip=1&key=yt6&lmt=1500797732386167&itag=18&sparams=clen,dur,ei,gir,id,initcwndbps,ip,ipbits,itag,lmt,mime,mm,mn,ms,mv,pl,ratebypass,requiressl,source,expire&source=youtube&clen=17430161&title=Keyboarders - Life on the grid
userscript.html?id=3bc56f06-a390-44ac-909b-f2125f745067:960 DYVAM - Info: itag43 url:https://r1---sn-nu5gi0c-npoe7.googlevideo.com/videoplayback?initcwndbps=2132500&ei=GLY5W9TqJMXMowOwh42AAw&dur=0.000&expire=1530530424&fexp=23709359&ipbits=0&mm=31,29&mn=sn-nu5gi0c-npoe7,sn-npoeen7k&mime=video/webm&id=o-ALtrXRViexFZ7jujD8ukskDIuNytp0pDC9HRvhHzrsHb&pl=23&mt=1530508733&mv=m&ms=au,rdu&ip=58.182.52.103&requiressl=yes&c=WEB&signature=76098C217BCA43D5D72B5F54DF716416AFC28950.37D536D9EF14D3AB4015F6EB8123C200D01FF851&ratebypass=yes&gir=yes&fvip=1&key=yt6&lmt=1500798741637452&itag=43&sparams=clen,dur,ei,gir,id,initcwndbps,ip,ipbits,itag,lmt,mime,mm,mn,ms,mv,pl,ratebypass,requiressl,source,expire&source=youtube&clen=22629679&title=Keyboarders - Life on the grid
userscript.html?id=3bc56f06-a390-44ac-909b-f2125f745067:960 DYVAM - Info: itag22 url:https://r1---sn-nu5gi0c-npoe7.googlevideo.com/videoplayback?c=WEB&initcwndbps=2132500&ei=GLY5W9TqJMXMowOwh42AAw&signature=7688A101A0A3254DBD4274F6BAC4D65B1583C4CE.B1940F6A8CD37E8B95B3ACF0BF2986E9D3650980&dur=178.654&itag=22&fvip=1&key=yt6&lmt=1500797999869441&expire=1530530424&sparams=dur,ei,id,initcwndbps,ip,ipbits,itag,lmt,mime,mm,mn,ms,mv,pl,ratebypass,requiressl,source,expire&fexp=23709359&ipbits=0&mt=1530508733&mm=31,29&mn=sn-nu5gi0c-npoe7,sn-npoeen7k&mime=video/mp4&id=o-ALtrXRViexFZ7jujD8ukskDIuNytp0pDC9HRvhHzrsHb&pl=23&source=youtube&mv=m&ms=au,rdu&ip=58.182.52.103&requiressl=yes&ratebypass=yes&title=Keyboarders - Life on the grid
```

I'm browsing from Singapore.

**Comment by volkirik** [comment]
There is no error in the log. Signature is correct, too.

The button is in player. Near settings button.


screenshot

**Pull request merged**
